---
- name: Install Prerequisites
  package:
    name:
      - python3
      - python3-pip
      - python3-setuptools
    state: present
    update_cache: true
  become: true

- name: Install Bashate
  pip:
    name: bashate
  become: true

