---

- name: update apt
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: source bashrc
  shell: source /home/{{ ansible_user }}/.bashrc

- name: source profile
  shell: source /Users/{{ ansible_user }}/.profile

- name: source bash profile
  shell: source /Users/{{ ansible_user }}/.bash_profile
