---
- name: Download Sublime Merge
  unarchive:
    src: https://download.sublimetext.com/sublime_merge_build_2020_mac.zip
    dest: /Users/{{ ansible_user }}/Downloads
    remote_src: true

- name: Copy Sublime Merge from Downloads to Applications
  shell: cp -r /Users/{{ ansible_user }}/Downloads/Sublime\ Merge.app /Applications

- name: Launch Sublime Merge
  shell: open -a Sublime\ Merge.app
