---
- name: Clone tfenv repo
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: /home/{{ ansible_user }}/.tfenv
    
- name: Update PATH
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export PATH="$HOME/.tfenv/bin:$PATH"'
    state: present

- name: Validate
  shell: which tfenv
  register: tfenv_result

- debug:
    var: tfenv_result
  
