---
- name: Install Workstation Tools on MacOS
  handlers:
    - include: handlers/main.yml
  hosts: 127.0.0.1
  connection: local
  roles:
#    - vimtext
#    - azcli_macos
#    - powershell_macos
    - nodejs_macos
    - markdownlint
    - yamllint_macos
    - bashate_macos
    - sublimetext_macos
#    - sublimemerge
#    - vault
#    - tfenv
#    - rbenv
#    - testkitchen
